[tools]
node = "20"
pnpm = "latest"
supabase = "latest"

[tasks.gen-schema]
run = "pnpm dlx supabase gen types typescript --linked > ./src/lib/schema.ts"
description = "Generate Supabase schema types"
